/**
 * Findable API
 * Findable Restful API 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface UserPreferences {
    employment_status?: string;

    current_status?: string;

    employment_type?: string;

    desired_salary?: number;

    desired_salary_period?: string;

    benefits?: boolean;

    available_from?: UserPreferences.AvailableFromEnum;

    start_time?: string;

    legal_usa?: boolean;

    only_current_location?: boolean;

    relocation?: boolean;

    locations?: Array<models.Location>;

}
export namespace UserPreferences {
    export enum AvailableFromEnum {
        Immediately = <any> 'immediately',
        OneWeek = <any> 'one week',
        TwoWeeks = <any> 'two weeks',
        OneMonth = <any> 'one month',
        From = <any> 'from'
    }
}
